# Generated by Django 6.0.3 on 2026-04-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_financialaccount_billreminder_incomesource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccount',
            name='account_type',
            field=models.CharField(
                choices=[
                    ('wallet', 'Wallet'),
                    ('savings', 'Savings'),
                    ('credit', 'Credit'),
                    ('loan', 'Loans'),
                    ('bank', 'Bank Account'),
                    ('ewallet', 'E-Wallet'),
                    ('cash', 'Cash'),
                ],
                max_length=20,
            ),
        ),
    ]
